### ISSUE TITLE
Bug: Latest update prevents enchants on other tools.

### ISSUE THREAD

**Issue by Akitori** [Fuzss/sneakycurses#6] opened 2021-03-01 22:52 UTC
Impaling on swords, power on crossbows, etc.

May be due to latest forge?

36.0.43 forge (1.16.5)

Sneaky Magic 1.3

**Comment by Fuzss** [comment] 2021-03-02 12:51
I got power first try, but yeah, impaling seems broken.

**Comment by Fuzss** [comment] 2021-03-02 13:05
Well, turns out after some testing impaling is working, it’s just pretty rare. This is partially due to it being a type of damage enchantment and therefore being mutually exclusive to sharpness, smite and bane of arthropods. 

Would probably be best to buff the internal weight of impaling a little, but I won’t do that in this mod.

**Comment by Akitori** [comment] 2021-03-02 13:24
I'm replicating and showing you the bug.

Video is here.

https://youtu.be/iPOakGcOrtU

configs
https://pastebin.com/4vANnsBf

https://pastebin.com/tLXX5Qn2

I don't know why this is occuring.

**Comment by Akitori** [comment] 2021-03-02 13:50
To further add to this confusion, using the previous version of Sneaky Magic (1.2.1.1, 1.16.4) works on the 1.16.5

Sneaky Magic 1.3 does NOT work at all for me.

**Comment by Fuzss** [comment] 2021-03-02 14:02
I see, thanks for the clarification. I’m still unable to reproduce the issue myself, so tracking this down won’t be easy.

**Comment by Akitori** [comment] 2021-03-02 22:29
everything i've done still has the items unable to be enchanted with things. I've cleared config, done entirely clean directories, and nothing seems to fix it.

I feel like i'm missing something obvious.

**Comment by Fuzss** [comment] 2021-03-03 08:46
No, it's my fault somehow. It's just weird that I've done all that as well and can't get it to break... 😅

**Comment by Akitori** [comment] 2021-03-03 09:49
are you testing in dev enviroment or modpack? If modpack, what forge version? I wanna see if its only specific forge issues or something. Maybe i'll try redownloading the mod

**Comment by Fuzss** [comment] 2021-03-05 21:34
Please try [this](https://mega.nz/file/2RMRTaJb#59ftqdsvdEMZ48fU-rFEADU0IFWpFMWIfXLgHCuDPeQ) version. If it doesn't work please send your `latest.log` found in `.minecraft/logs`.

**Comment by Akitori** [comment] 2021-03-06 04:46
it works, dunno what you did to fix it!

**Comment by Fuzss** [comment] 2021-03-06 08:02
Awesome! Can you actually still send your `latest.log`? Still not 100% sure about the source of your issue, so the log will help. Doesn't matter which version of Sneaky Magic you use, even the new one is fine.

**Comment by Akitori** [comment] 2021-03-06 10:37
https://pastebin.com/0jyCcLg2

that's the latest log with the fixed sneaky magic, idk what happeneed

**Comment by Fuzss** [comment] 2021-03-06 11:13
Great, thank you so much! That explains everything.

Turns out the common config isn't reloaded for some reason on start-up on your system (client config on the other hand is). The enchantment compatibility part of Sneaky Magic relies on the config being reloaded once though.

What I've done now is simply forcing a config reload when the game is about to start, so the config will be reloaded once for sure, possibly even twice.

I'll close the issue as soon as the new version is released on CurseForge.

**Comment by Fuzss** [comment] 2021-03-07 15:46
Fixed in v.1.3.1.

**Closed as completed by Fuzss** 2021-03-07 15:46 UTC
