### ISSUE TITLE
Calling client config when it is not yet available with Apotheosis

### ISSUE THREAD

**Issue by ghost** [Fuzss/sneakycurses#12] opened 2022-05-10 02:46 UTC
Works fine but the error is a bit weird, maybe I just don't know
[Log-918](https://paste.ee/p/ZYSp3#s=0&l=918)

Minecraft 1.18.2
Forge 40.1.19
PuzzlesLib v3.3.3
Apotheosis 5.3.5

**Comment by Fuzss** [comment] 2022-08-19 11:40
Duplicate of #14.

**Closed as completed by Fuzss** 2022-08-19 11:40 UTC
